import type { Slug } from 'react-native-body-highlighter';

/**
 * Base gerada automaticamente a partir do dataset RepDB
 * (sergei-argutin/exercise-dataset, 571 exercicios --
 * licenca free-tier com atribuicao, mesma ja usada nos 29 exercicios
 * curados de exerciseLibrary.ts: "Exercise data by RepDB (repdb.co)").
 *
 * NAO EDITAR ESTE ARQUIVO A MAO. Pra corrigir a traducao de um exercicio
 * especifico, editar mobile/constants/exerciseTranslationOverrides.json
 * (chave = "id" abaixo, valor = nome corrigido em portugues) -- exerciseLibrary.ts
 * aplica o override por cima do valor de "name" aqui na hora de montar a
 * lista final, sem precisar gerar este arquivo de novo.
 *
 * QUALIDADE DA TRADUCAO: os nomes originais estao so em ingles/alemao/
 * espanhol no RepDB -- traduzidos pra portugues via dicionario curado a
 * mao (nao um modelo de traducao automatica rodando linha a linha).
 * Cobertura: 571 de 601 exercicios do dataset (os outros 29
 * ja existiam na lista curada com ilustracao -- mesmo id RepDB, ver
 * CURATED_REPDB_IDS no script gerador -- entao nao foram duplicados
 * aqui). Terminologia de academia costuma ser bem padronizada, entao a
 * traducao tende a ficar correta pra maioria, mas numa lista deste
 * tamanho E ESPERADO ter erro pontual ou termo pouco natural em alguns —
 * revisar uma amostra antes de considerar a base "pronta", nao os
 * 571 de uma vez. Ver o script gerador (nao versionado no
 * repo) pra reproduzir/regenerar isto do zero se o dataset RepDB for
 * atualizado.
 *
 * SEM midia de execucao (imagens de pose ou video) de proposito -- so os
 * 29 exercicios curados de antes desta tarefa tem esse tipo de midia
 * (decisao separada, ver comentario no topo de exerciseLibrary.ts). Um
 * exercicio desta lista cai no placeholder normal (ExerciseVideoBlock),
 * igual a qualquer exercicio sem video hoje.
 *
 * "id": identificador original do RepDB -- usado so pra aplicar overrides
 * de traducao, nunca aparece na UI (a UI mostra "name").
 */
export interface RepDBRawEntry {
  id: string;
  name: string;
  muscles: Slug[];
}

export const REPDB_EXERCISES: RepDBRawEntry[] = [
  { id: "bicycle-crunch", name: "Abdominal Bicicleta", muscles: ['obliques', 'abs'] },
  { id: "jackknife-sit-up", name: "Abdominal Canivete (Jackknife)", muscles: ['abs'] },
  { id: "cross-body-crunch", name: "Abdominal Cruzado", muscles: ['obliques'] },
  { id: "decline-crunch", name: "Abdominal Declinado", muscles: ['abs'] },
  { id: "v-ups", name: "Abdominal em V (V-Up)", muscles: ['quadriceps', 'abs'] },
  { id: "weighted-wall-crunch", name: "Abdominal na Parede com Peso", muscles: ['abs'] },
  { id: "cable-crunch", name: "Abdominal no Cabo", muscles: ['abs'] },
  { id: "reverse-crunches", name: "Abdominal Reverso", muscles: ['abs'] },
  { id: "machine-seated-crunch", name: "Abdominal Sentado na Máquina", muscles: ['abs'] },
  { id: "sit-ups", name: "Abdominal Supra (Sit-Up)", muscles: ['quadriceps', 'abs'] },
  { id: "side-lying-hip-abduction", name: "Abdução de Quadril Deitado de Lado", muscles: ['gluteal'] },
  { id: "side-lying-hip-abduction-hold", name: "Abdução de Quadril Deitado de Lado, Isométrica", muscles: ['gluteal'] },
  { id: "banded-standing-hip-abduction", name: "Abdução de Quadril em Pé com Elástico", muscles: ['gluteal'] },
  { id: "banded-seated-hip-abduction", name: "Abdução de Quadril Sentado com Elástico", muscles: ['gluteal'] },
  { id: "side-lying-hip-adduction", name: "Adução de Quadril Deitado de Lado", muscles: ['adductors'] },
  { id: "side-lying-hip-adduction-hold", name: "Adução de Quadril Deitado de Lado, Isométrica", muscles: ['adductors'] },
  { id: "banded-standing-hip-adduction", name: "Adução de Quadril em Pé com Elástico", muscles: ['adductors'] },
  { id: "low-lunge", name: "Afundo Baixo", muscles: ['quadriceps'] },
  { id: "low-lunge-to-half-split", name: "Afundo Baixo para Meio Splits", muscles: ['hamstring'] },
  { id: "walking-lunge", name: "Afundo Caminhando", muscles: ['gluteal', 'quadriceps'] },
  { id: "barbell-lunge", name: "Afundo com Barra", muscles: ['gluteal', 'quadriceps'] },
  { id: "kettlebell-lunge-press", name: "Afundo com Desenvolvimento no Kettlebell", muscles: ['deltoids', 'gluteal', 'quadriceps'] },
  { id: "db-lunge", name: "Afundo com Halteres", muscles: ['gluteal', 'quadriceps'] },
  { id: "trx-lunge", name: "Afundo com TRX", muscles: ['gluteal', 'quadriceps'] },
  { id: "crescent-lunge", name: "Afundo Crescente", muscles: ['gluteal', 'quadriceps'] },
  { id: "revolved-crescent-lunge", name: "Afundo Crescente Revolvido", muscles: ['obliques', 'quadriceps'] },
  { id: "kettlebell-goblet-lunge", name: "Afundo Goblet com Kettlebell", muscles: ['gluteal', 'quadriceps'] },
  { id: "side-lunge", name: "Afundo Lateral", muscles: ['gluteal', 'quadriceps'] },
  { id: "plyo-lunge", name: "Afundo Pliométrico", muscles: ['gluteal', 'quadriceps'] },
  { id: "reverse-lunge", name: "Afundo Reverso", muscles: ['gluteal', 'quadriceps'] },
  { id: "kettlebell-reverse-lunge", name: "Afundo Reverso com Kettlebell", muscles: ['gluteal', 'quadriceps'] },
  { id: "bodyweight-reverse-lunge", name: "Afundo Reverso com Peso Corporal", muscles: ['gluteal', 'quadriceps'] },
  { id: "smith-machine-reverse-lunge", name: "Afundo Reverso no Smith", muscles: ['gluteal', 'quadriceps'] },
  { id: "kettlebell-offset-reverse-lunge-and-press", name: "Afundo Reverso Offset com Desenvolvimento no Kettlebell", muscles: ['deltoids', 'gluteal', 'quadriceps'] },
  { id: "kettlebell-rotational-lunge", name: "Afundo Rotacional com Kettlebell", muscles: ['gluteal', 'quadriceps'] },
  { id: "bulgarian-split-squat", name: "Agachamento Búlgaro", muscles: ['gluteal', 'quadriceps'] },
  { id: "kettlebell-bulgarian-split-squat", name: "Agachamento Búlgaro com Kettlebell", muscles: ['gluteal', 'quadriceps'] },
  { id: "split-squat", name: "Agachamento Búlgaro Estático (Split Squat)", muscles: ['gluteal', 'quadriceps'] },
  { id: "dumbbell-split-squat", name: "Agachamento Búlgaro Estático com Halteres", muscles: ['gluteal', 'quadriceps'] },
  { id: "smith-machine-split-squat", name: "Agachamento Búlgaro Estático no Smith", muscles: ['gluteal', 'quadriceps'] },
  { id: "smith-machine-bulgarian-split", name: "Agachamento Búlgaro no Smith", muscles: ['gluteal', 'quadriceps'] },
  { id: "heel-elevated-squat", name: "Agachamento com Calço no Calcanhar", muscles: ['gluteal', 'quadriceps'] },
  { id: "banded-squat", name: "Agachamento com Elástico", muscles: ['gluteal', 'quadriceps'] },
  { id: "db-squat", name: "Agachamento com Halteres", muscles: ['gluteal', 'quadriceps'] },
  { id: "kettlebell-squat", name: "Agachamento com Kettlebell", muscles: ['quadriceps'] },
  { id: "jump-squat", name: "Agachamento com Salto", muscles: ['gluteal', 'quadriceps'] },
  { id: "trx-squat", name: "Agachamento com TRX", muscles: ['gluteal', 'quadriceps'] },
  { id: "cossack-squat", name: "Agachamento Cossaco", muscles: ['gluteal', 'quadriceps'] },
  { id: "front-squat", name: "Agachamento Frontal", muscles: ['gluteal', 'quadriceps'] },
  { id: "dumbbell-front-squat", name: "Agachamento Frontal com Halteres", muscles: ['gluteal', 'quadriceps'] },
  { id: "smith-machine-front-squat", name: "Agachamento Frontal no Smith", muscles: ['gluteal', 'quadriceps'] },
  { id: "one-arm-kettlebell-front-squat", name: "Agachamento Frontal Unilateral com Kettlebell", muscles: ['gluteal', 'quadriceps'] },
  { id: "goblet-squat", name: "Agachamento Goblet", muscles: ['gluteal', 'quadriceps'] },
  { id: "hack-squat", name: "Agachamento Hack", muscles: ['gluteal', 'quadriceps'] },
  { id: "bodyweight-squat", name: "Agachamento Livre (Peso Corporal)", muscles: ['gluteal', 'quadriceps'] },
  { id: "box-squat", name: "Agachamento na Caixa", muscles: ['gluteal', 'quadriceps'] },
  { id: "stability-ball-wall-squat", name: "Agachamento na Parede com Bola Suíça", muscles: ['gluteal', 'quadriceps'] },
  { id: "smith-machine-squat", name: "Agachamento no Smith", muscles: ['gluteal', 'quadriceps'] },
  { id: "overhead-squat", name: "Agachamento Overhead", muscles: ['gluteal', 'quadriceps'] },
  { id: "pause-squat", name: "Agachamento Pausado", muscles: ['gluteal', 'quadriceps'] },
  { id: "pistol-squat", name: "Agachamento Pistol", muscles: ['gluteal', 'quadriceps'] },
  { id: "dumbbell-pistol-squat", name: "Agachamento Pistol com Halteres", muscles: ['gluteal', 'quadriceps'] },
  { id: "kettlebell-pistol-squat", name: "Agachamento Pistol com Kettlebell", muscles: ['gluteal', 'quadriceps'] },
  { id: "trx-pistol-squat", name: "Agachamento Pistol com TRX", muscles: ['gluteal', 'quadriceps'] },
  { id: "db-somersault-squat", name: "Agachamento Somersault com Halteres", muscles: ['gluteal', 'quadriceps'] },
  { id: "sumo-squat", name: "Agachamento Sumô", muscles: ['gluteal', 'quadriceps'] },
  { id: "db-sumo-squat", name: "Agachamento Sumô com Halteres", muscles: ['gluteal', 'quadriceps'] },
  { id: "butterfly-stretch", name: "Alongamento Borboleta", muscles: ['adductors'] },
  { id: "bench-bulgarian-split-stretch", name: "Alongamento Búlgaro no Banco", muscles: ['quadriceps'] },
  { id: "banded-adductor-stretch", name: "Alongamento de Adutor com Elástico", muscles: ['adductors'] },
  { id: "bench-adductor-stretch", name: "Alongamento de Adutor no Banco", muscles: ['adductors'] },
  { id: "banded-it-band-stretch", name: "Alongamento de Banda IT com Elástico", muscles: ['gluteal'] },
  { id: "banded-rear-delt-stretch", name: "Alongamento de Deltoide Posterior com Elástico", muscles: ['deltoids'] },
  { id: "banded-lat-stretch", name: "Alongamento de Dorsal com Elástico", muscles: ['upper-back'] },
  { id: "bench-lat-stretch", name: "Alongamento de Dorsal no Banco", muscles: ['upper-back'] },
  { id: "kneeling-hip-flexor-stretch", name: "Alongamento de Flexor de Quadril Ajoelhado", muscles: ['quadriceps'] },
  { id: "bench-figure-4-glute-stretch", name: "Alongamento de Glúteo Figura 4 no Banco", muscles: ['gluteal'] },
  { id: "banded-shoulder-stretch", name: "Alongamento de Ombro com Elástico", muscles: ['deltoids'] },
  { id: "cross-body-shoulder-stretch", name: "Alongamento de Ombro Cruzado", muscles: ['deltoids'] },
  { id: "banded-calf-stretch", name: "Alongamento de Panturrilha com Elástico", muscles: ['calves'] },
  { id: "standing-calf-stretch", name: "Alongamento de Panturrilha em Pé", muscles: ['calves'] },
  { id: "bench-calf-stretch", name: "Alongamento de Panturrilha no Banco", muscles: ['calves'] },
  { id: "banded-chest-stretch", name: "Alongamento de Peito com Elástico", muscles: ['chest'] },
  { id: "bench-chest-stretch", name: "Alongamento de Peito no Banco", muscles: ['chest'] },
  { id: "doorway-chest-stretch", name: "Alongamento de Peito no Vão da Porta", muscles: ['chest'] },
  { id: "banded-hamstring-stretch", name: "Alongamento de Posterior com Elástico", muscles: ['hamstring'] },
  { id: "bench-hamstring-stretch", name: "Alongamento de Posterior no Banco", muscles: ['hamstring'] },
  { id: "kneeling-wrist-stretch", name: "Alongamento de Punho Ajoelhado", muscles: ['forearm'] },
  { id: "standing-quad-stretch", name: "Alongamento de Quadríceps em Pé", muscles: ['quadriceps'] },
  { id: "bench-couch-stretch", name: "Alongamento de Quadríceps no Banco (Couch Stretch)", muscles: ['quadriceps'] },
  { id: "banded-ankle-stretch", name: "Alongamento de Tornozelo com Elástico", muscles: ['calves'] },
  { id: "bench-ankle-stretch", name: "Alongamento de Tornozelo no Banco", muscles: ['calves'] },
  { id: "overhead-triceps-stretch", name: "Alongamento de Tríceps Acima da Cabeça", muscles: ['triceps'] },
  { id: "banded-triceps-stretch", name: "Alongamento de Tríceps com Elástico", muscles: ['triceps'] },
  { id: "cat-stretch", name: "Alongamento do Gato", muscles: ['lower-back'] },
  { id: "lizard-stretch", name: "Alongamento do Lagarto", muscles: ['adductors', 'quadriceps'] },
  { id: "pigeon-stretch", name: "Alongamento do Pombo", muscles: ['gluteal'] },
  { id: "seated-straddle-stretch", name: "Alongamento em Afastamento Sentado", muscles: ['adductors', 'hamstring'] },
  { id: "banded-figure-4-stretch", name: "Alongamento Figura 4 com Elástico", muscles: ['gluteal'] },
  { id: "knee-to-chest-stretch", name: "Alongamento Joelho ao Peito", muscles: ['gluteal'] },
  { id: "neck-side-stretch", name: "Alongamento Lateral de Pescoço", muscles: ['trapezius'] },
  { id: "dumbbell-snatch", name: "Arranco com Halteres", muscles: ['deltoids', 'gluteal', 'trapezius'] },
  { id: "medicine-ball-slam", name: "Arremesso de Bola Medicinal (Slam Ball)", muscles: ['abs'] },
  { id: "back-lever", name: "Back Lever", muscles: ['lower-back', 'upper-back'] },
  { id: "half-kneeling-hip-flexor-rock", name: "Balanço de Flexor de Quadril Meio Ajoelhado", muscles: ['quadriceps'] },
  { id: "chin-ups", name: "Barra Fixa (Pegada Supinada)", muscles: ['biceps', 'upper-back'] },
  { id: "archer-pull-ups", name: "Barra Fixa Archer", muscles: ['upper-back'] },
  { id: "assisted-pull-ups", name: "Barra Fixa Assistida", muscles: ['upper-back'] },
  { id: "band-assisted-pull-ups", name: "Barra Fixa Assistida com Elástico", muscles: ['upper-back'] },
  { id: "behind-the-neck-pull-ups", name: "Barra Fixa Atrás da Nuca", muscles: ['upper-back'] },
  { id: "weighted-pull-up", name: "Barra Fixa com Peso", muscles: ['upper-back'] },
  { id: "scapular-pull-ups", name: "Barra Fixa Escapular", muscles: ['upper-back', 'trapezius'] },
  { id: "negative-pull-ups", name: "Barra Fixa Negativa", muscles: ['upper-back'] },
  { id: "pause-pull-up", name: "Barra Fixa Pausada", muscles: ['upper-back'] },
  { id: "wide-grip-pull-ups", name: "Barra Fixa Pegada Aberta", muscles: ['upper-back'] },
  { id: "close-grip-pull-ups", name: "Barra Fixa Pegada Fechada", muscles: ['biceps', 'upper-back'] },
  { id: "neutral-grip-pull-ups", name: "Barra Fixa Pegada Neutra", muscles: ['upper-back'] },
  { id: "battle-ropes", name: "Battle Rope (Corda Naval)", muscles: ['deltoids', 'upper-back'] },
  { id: "battle-rope-double-slam", name: "Battle Rope, Golpe Duplo", muscles: ['deltoids', 'upper-back'] },
  { id: "stationary-bike", name: "Bicicleta Ergométrica", muscles: ['quadriceps'] },
  { id: "air-bike", name: "Bicicleta Ergométrica (Air Bike)", muscles: ['hamstring', 'quadriceps'] },
  { id: "bird-dog", name: "Bird-Dog (Cão de Aponte)", muscles: ['lower-back', 'abs'] },
  { id: "bird-dog-hold", name: "Bird-Dog Isométrico", muscles: ['lower-back', 'abs'] },
  { id: "good-morning", name: "Bom Dia (Good Morning)", muscles: ['lower-back', 'gluteal', 'hamstring'] },
  { id: "banded-good-morning", name: "Bom Dia com Elástico", muscles: ['gluteal', 'hamstring'] },
  { id: "bodyweight-good-morning", name: "Bom Dia com Peso Corporal", muscles: ['lower-back', 'hamstring'] },
  { id: "smith-machine-good-morning", name: "Bom Dia no Smith", muscles: ['lower-back', 'hamstring'] },
  { id: "burpees", name: "Burpee", muscles: ['gluteal', 'chest', 'quadriceps'] },
  { id: "downward-dog", name: "Cachorro Olhando para Baixo", muscles: ['calves', 'hamstring'] },
  { id: "downward-dog-to-knee-drive", name: "Cachorro Olhando para Baixo com Elevação de Joelho", muscles: ['quadriceps', 'abs'] },
  { id: "downward-dog-knee-tuck", name: "Cachorro Olhando para Baixo com Joelho ao Peito", muscles: ['quadriceps', 'abs'] },
  { id: "three-legged-dog", name: "Cachorro Olhando para Baixo com Três Apoios", muscles: ['deltoids', 'gluteal'] },
  { id: "downward-dog-to-low-lunge", name: "Cachorro Olhando para Baixo para Afundo Baixo", muscles: ['quadriceps'] },
  { id: "downward-dog-to-upward-dog", name: "Cachorro Olhando para Baixo para Cachorro Olhando para Cima", muscles: ['deltoids', 'lower-back'] },
  { id: "downward-dog-to-plank", name: "Cachorro Olhando para Baixo para Prancha", muscles: ['deltoids', 'abs'] },
  { id: "downward-dog-pedal", name: "Cachorro Olhando para Baixo, Pedalada", muscles: ['calves'] },
  { id: "upward-dog", name: "Cachorro Olhando para Cima", muscles: ['lower-back', 'triceps'] },
  { id: "single-leg-extension", name: "Cadeira Extensora Unilateral", muscles: ['quadriceps'] },
  { id: "seated-leg-curl", name: "Cadeira Flexora", muscles: ['hamstring'] },
  { id: "wall-sit", name: "Cadeira na Parede (Wall Sit)", muscles: ['gluteal', 'quadriceps'] },
  { id: "walking", name: "Caminhada", muscles: ['calves', 'quadriceps'] },
  { id: "heel-to-toe-walk", name: "Caminhada Calcanhar-Ponta do Pé", muscles: ['gluteal', 'calves'] },
  { id: "double-db-overhead-carry", name: "Caminhada com 2 Halteres Acima da Cabeça", muscles: ['deltoids'] },
  { id: "double-kettlebell-overhead-carry", name: "Caminhada com 2 Kettlebells Acima da Cabeça", muscles: ['deltoids'] },
  { id: "db-overhead-carry", name: "Caminhada com Halteres Acima da Cabeça", muscles: ['deltoids'] },
  { id: "kettlebell-overhead-carry", name: "Caminhada com Kettlebell Acima da Cabeça", muscles: ['deltoids'] },
  { id: "suitcase-carry", name: "Caminhada com Mala (Suitcase Carry)", muscles: ['forearm', 'obliques', 'lower-back'] },
  { id: "dumbbell-farmers-walk", name: "Caminhada do Fazendeiro com Halteres", muscles: ['forearm', 'trapezius'] },
  { id: "kettlebell-farmers-walk", name: "Caminhada do Fazendeiro com Kettlebell", muscles: ['forearm', 'trapezius'] },
  { id: "incline-treadmill-walk", name: "Caminhada Inclinada na Esteira", muscles: ['gluteal', 'quadriceps'] },
  { id: "banded-lateral-walk", name: "Caminhada Lateral com Elástico", muscles: ['gluteal'] },
  { id: "banded-sumo-walk", name: "Caminhada Sumô com Elástico", muscles: ['gluteal'] },
  { id: "clamshells", name: "Clamshell (Concha)", muscles: ['gluteal'] },
  { id: "banded-clamshell", name: "Clamshell com Elástico", muscles: ['gluteal'] },
  { id: "clamshells-hold", name: "Clamshell Isométrico (Concha)", muscles: ['gluteal'] },
  { id: "clean", name: "Clean (Levantamento Olímpico)", muscles: ['gluteal', 'quadriceps'] },
  { id: "clean-and-jerk", name: "Clean and Jerk", muscles: ['deltoids', 'gluteal', 'quadriceps'] },
  { id: "double-kettlebell-clean-and-press", name: "Clean and Press com 2 Kettlebells", muscles: ['deltoids'] },
  { id: "double-kettlebell-clean", name: "Clean com 2 Kettlebells", muscles: ['gluteal', 'hamstring'] },
  { id: "cocoons", name: "Cocoon (Abdominal em C)", muscles: ['abs'] },
  { id: "glute-kickback", name: "Coice de Glúteo (Kickback)", muscles: ['gluteal'] },
  { id: "glute-kickback-hold", name: "Coice de Glúteo Isométrico", muscles: ['gluteal'] },
  { id: "cable-kickback", name: "Coice de Glúteo no Cabo", muscles: ['gluteal'] },
  { id: "running", name: "Corrida", muscles: ['calves', 'quadriceps'] },
  { id: "high-knees", name: "Corrida Estacionária (High Knees)", muscles: ['quadriceps'] },
  { id: "treadmill-running", name: "Corrida na Esteira", muscles: ['calves', 'quadriceps'] },
  { id: "decline-db-fly", name: "Crucifixo Declinado com Halteres", muscles: ['chest'] },
  { id: "trx-y-fly", name: "Crucifixo em Y no TRX", muscles: ['deltoids', 'trapezius'] },
  { id: "incline-dumbbell-fly", name: "Crucifixo Inclinado com Halteres", muscles: ['chest'] },
  { id: "rear-delt-fly", name: "Crucifixo Inverso", muscles: ['deltoids', 'upper-back'] },
  { id: "dumbbell-reverse-fly", name: "Crucifixo Inverso com Halteres", muscles: ['deltoids'] },
  { id: "machine-chest-fly", name: "Crucifixo na Máquina", muscles: ['chest'] },
  { id: "cable-fly", name: "Crucifixo no Cabo", muscles: ['chest'] },
  { id: "dead-bug", name: "Dead Bug", muscles: ['abs'] },
  { id: "dead-bug-hold", name: "Dead Bug Isométrico", muscles: ['abs'] },
  { id: "double-kettlebell-dead-clean", name: "Dead Clean com 2 Kettlebells", muscles: ['gluteal', 'hamstring'] },
  { id: "dead-hang", name: "Dead Hang (Pendurado na Barra)", muscles: ['forearm'] },
  { id: "ring-dead-hang", name: "Dead Hang nas Argolas", muscles: ['forearm'] },
  { id: "arnold-press", name: "Desenvolvimento Arnold", muscles: ['deltoids'] },
  { id: "behind-the-neck-press", name: "Desenvolvimento Atrás da Nuca", muscles: ['deltoids'] },
  { id: "one-arm-kettlebell-bottoms-up-press", name: "Desenvolvimento Bottoms-Up Unilateral com Kettlebell", muscles: ['deltoids'] },
  { id: "double-kettlebell-overhead-press", name: "Desenvolvimento com 2 Kettlebells", muscles: ['deltoids', 'triceps'] },
  { id: "bodyweight-overhead-press", name: "Desenvolvimento com Peso Corporal", muscles: ['deltoids', 'triceps'] },
  { id: "ohp", name: "Desenvolvimento Militar com Barra", muscles: ['deltoids'] },
  { id: "paused-ohp", name: "Desenvolvimento Militar com Barra, Pausado", muscles: ['deltoids'] },
  { id: "seated-barbell-overhead-press", name: "Desenvolvimento Militar Sentado com Barra", muscles: ['deltoids'] },
  { id: "machine-shoulder-press", name: "Desenvolvimento na Máquina", muscles: ['deltoids'] },
  { id: "landmine-press", name: "Desenvolvimento no Landmine", muscles: ['deltoids', 'chest'] },
  { id: "smith-machine-shoulder-press", name: "Desenvolvimento no Smith", muscles: ['deltoids'] },
  { id: "seated-db-press", name: "Desenvolvimento Sentado com Halteres", muscles: ['deltoids'] },
  { id: "seated-smith-machine-shoulder-press", name: "Desenvolvimento Sentado no Smith", muscles: ['deltoids'] },
  { id: "one-arm-kettlebell-shoulder-press", name: "Desenvolvimento Unilateral com Kettlebell", muscles: ['deltoids'] },
  { id: "single-arm-machine-shoulder-press", name: "Desenvolvimento Unilateral na Máquina", muscles: ['deltoids'] },
  { id: "one-arm-landmine-press", name: "Desenvolvimento Unilateral no Landmine", muscles: ['deltoids', 'chest'] },
  { id: "dragon-flag", name: "Dragon Flag", muscles: ['abs'] },
  { id: "hanging-knee-raise", name: "Elevação de Joelhos na Barra", muscles: ['quadriceps', 'abs'] },
  { id: "captains-chair-knee-raise", name: "Elevação de Joelhos na Cadeira Romana", muscles: ['quadriceps', 'abs'] },
  { id: "barbell-calf-raise", name: "Elevação de Panturrilha com Barra", muscles: ['calves'] },
  { id: "dumbbell-calf-raise", name: "Elevação de Panturrilha com Halteres", muscles: ['calves'] },
  { id: "bodyweight-calf-raise", name: "Elevação de Panturrilha com Peso Corporal", muscles: ['calves'] },
  { id: "donkey-calf-raise", name: "Elevação de Panturrilha Donkey", muscles: ['calves'] },
  { id: "plate-loaded-donkey-calf-raise", name: "Elevação de Panturrilha Donkey com Anilha", muscles: ['calves'] },
  { id: "standing-calf-raise", name: "Elevação de Panturrilha em Pé", muscles: ['calves'] },
  { id: "hack-squat-calf-raise", name: "Elevação de Panturrilha no Hack", muscles: ['calves'] },
  { id: "smith-machine-calf-raise", name: "Elevação de Panturrilha no Smith", muscles: ['calves'] },
  { id: "seated-calf-raise", name: "Elevação de Panturrilha Sentado", muscles: ['calves'] },
  { id: "single-leg-calf-raise", name: "Elevação de Panturrilha Unilateral", muscles: ['calves'] },
  { id: "hanging-leg-raise", name: "Elevação de Pernas na Barra", muscles: ['quadriceps', 'abs'] },
  { id: "captains-chair-leg-raise", name: "Elevação de Pernas na Cadeira Romana", muscles: ['quadriceps', 'abs'] },
  { id: "banded-kneeling-hip-thrust", name: "Elevação de Quadril Ajoelhado com Elástico", muscles: ['gluteal'] },
  { id: "banded-hip-thrust", name: "Elevação de Quadril com Elástico", muscles: ['gluteal'] },
  { id: "dumbbell-hip-thrust", name: "Elevação de Quadril com Halteres", muscles: ['gluteal'] },
  { id: "kettlebell-hip-thrust", name: "Elevação de Quadril com Kettlebell", muscles: ['gluteal'] },
  { id: "smith-machine-hip-thrust", name: "Elevação de Quadril no Smith", muscles: ['gluteal'] },
  { id: "barbell-front-raise", name: "Elevação Frontal com Barra", muscles: ['deltoids'] },
  { id: "ez-bar-front-raise", name: "Elevação Frontal com Barra W", muscles: ['deltoids'] },
  { id: "straight-bar-cable-front-raise", name: "Elevação Frontal na Barra Reta (Cabo)", muscles: ['deltoids'] },
  { id: "cable-front-raise", name: "Elevação Frontal no Cabo", muscles: ['deltoids'] },
  { id: "plate-loaded-lateral-raise", name: "Elevação Lateral com Anilha", muscles: ['deltoids'] },
  { id: "bodyweight-lateral-raise", name: "Elevação Lateral com Peso Corporal", muscles: ['deltoids'] },
  { id: "side-lying-lateral-raise", name: "Elevação Lateral Deitado de Lado", muscles: ['deltoids'] },
  { id: "cable-lateral-raise", name: "Elevação Lateral no Cabo", muscles: ['deltoids'] },
  { id: "seated-dumbbell-lateral-raise", name: "Elevação Lateral Sentado com Halteres", muscles: ['deltoids'] },
  { id: "single-arm-plate-loaded-lateral-raise", name: "Elevação Lateral Unilateral com Anilha", muscles: ['deltoids'] },
  { id: "elliptical-trainer", name: "Elíptico", muscles: ['gluteal', 'quadriceps'] },
  { id: "plate-loaded-shrug", name: "Encolhimento com Anilha", muscles: ['trapezius'] },
  { id: "behind-the-back-barbell-shrug", name: "Encolhimento com Barra por Trás das Costas", muscles: ['trapezius'] },
  { id: "ez-bar-shrug", name: "Encolhimento com Barra W", muscles: ['trapezius'] },
  { id: "db-shrug", name: "Encolhimento com Halteres", muscles: ['trapezius'] },
  { id: "chest-supported-dumbbell-shrug", name: "Encolhimento com Halteres Apoiado no Banco", muscles: ['trapezius'] },
  { id: "kettlebell-shrug", name: "Encolhimento com Kettlebell", muscles: ['trapezius'] },
  { id: "smith-machine-shrug", name: "Encolhimento no Smith", muscles: ['trapezius'] },
  { id: "thread-the-needle", name: "Enfiar a Agulha", muscles: ['deltoids', 'trapezius'] },
  { id: "thread-the-needle-flow", name: "Enfiar a Agulha (Fluxo)", muscles: ['obliques', 'trapezius'] },
  { id: "stair-climber", name: "Escada Ergométrica (Stair Climber)", muscles: ['gluteal', 'quadriceps'] },
  { id: "rope-climb", name: "Escalada de Corda", muscles: ['upper-back'] },
  { id: "mountain-climbers", name: "Escalador (Mountain Climber)", muscles: ['quadriceps', 'abs'] },
  { id: "kettlebell-overhead-tricep-extension", name: "Extensão de Tríceps Acima da Cabeça com Kettlebell", muscles: ['triceps'] },
  { id: "dumbbell-tricep-extension", name: "Extensão de Tríceps com Halteres", muscles: ['triceps'] },
  { id: "machine-triceps-extension", name: "Extensão de Tríceps na Máquina", muscles: ['triceps'] },
  { id: "trx-tricep-extension", name: "Extensão de Tríceps no TRX", muscles: ['triceps'] },
  { id: "seated-dumbbell-tricep-extension", name: "Extensão de Tríceps Sentado com Halteres", muscles: ['triceps'] },
  { id: "back-extension", name: "Extensão Lombar (Banco Romano)", muscles: ['lower-back'] },
  { id: "machine-back-extension", name: "Extensão Lombar na Máquina", muscles: ['lower-back'] },
  { id: "banded-terminal-knee-extension", name: "Extensão Terminal de Joelho com Elástico", muscles: ['quadriceps'] },
  { id: "dumbbell-face-pull", name: "Face Pull com Halteres", muscles: ['deltoids', 'upper-back'] },
  { id: "ring-face-pull", name: "Face Pull nas Argolas", muscles: ['deltoids', 'upper-back'] },
  { id: "trx-face-pull", name: "Face Pull no TRX", muscles: ['deltoids', 'upper-back'] },
  { id: "banded-fire-hydrant", name: "Fire Hydrant com Elástico", muscles: ['gluteal'] },
  { id: "archer-push-ups", name: "Flexão de Braço Archer", muscles: ['chest'] },
  { id: "stability-ball-push-up", name: "Flexão de Braço com Bola Suíça", muscles: ['chest'] },
  { id: "knee-push-ups", name: "Flexão de Braço com Joelhos Apoiados", muscles: ['chest'] },
  { id: "stability-ball-push-up-hands-on-ball", name: "Flexão de Braço com Mãos na Bola Suíça", muscles: ['chest'] },
  { id: "clap-push-ups", name: "Flexão de Braço com Palma", muscles: ['chest'] },
  { id: "decline-push-up", name: "Flexão de Braço Declinada", muscles: ['chest'] },
  { id: "diamond-push-ups", name: "Flexão de Braço Diamante", muscles: ['chest', 'triceps'] },
  { id: "deficit-push-ups", name: "Flexão de Braço em Déficit", muscles: ['chest'] },
  { id: "handstand-push-ups", name: "Flexão de Braço em Parada de Mãos", muscles: ['deltoids', 'triceps'] },
  { id: "incline-push-ups", name: "Flexão de Braço Inclinada", muscles: ['chest'] },
  { id: "wall-push-ups", name: "Flexão de Braço na Parede", muscles: ['chest'] },
  { id: "ring-push-up", name: "Flexão de Braço nas Argolas", muscles: ['chest', 'triceps'] },
  { id: "wide-grip-push-ups", name: "Flexão de Braço Pegada Aberta", muscles: ['chest'] },
  { id: "close-grip-push-ups", name: "Flexão de Braço Pegada Fechada", muscles: ['chest', 'triceps'] },
  { id: "pike-push-ups", name: "Flexão de Braço Pike", muscles: ['deltoids'] },
  { id: "plyo-push-up", name: "Flexão de Braço Pliométrica", muscles: ['chest', 'triceps'] },
  { id: "pseudo-planche-push-ups", name: "Flexão de Braço Pseudo Planche", muscles: ['deltoids', 'chest'] },
  { id: "standing-side-bend", name: "Flexão Lateral em Pé", muscles: ['obliques'] },
  { id: "standing-side-bend-flow", name: "Flexão Lateral em Pé (Fluxo)", muscles: ['obliques'] },
  { id: "isometric-neck-side", name: "Flexão Lateral Isométrica de Pescoço", muscles: ['trapezius'] },
  { id: "wide-legged-forward-fold", name: "Flexão para Frente com Pernas Afastadas", muscles: ['adductors', 'hamstring'] },
  { id: "standing-forward-fold", name: "Flexão para Frente em Pé", muscles: ['hamstring'] },
  { id: "standing-forward-fold-to-half-lift", name: "Flexão para Frente em Pé para Meia Elevação", muscles: ['lower-back', 'hamstring'] },
  { id: "seated-forward-fold", name: "Flexão para Frente Sentado", muscles: ['hamstring'] },
  { id: "ball-leg-curl", name: "Flexora com Bola Suíça", muscles: ['hamstring'] },
  { id: "trx-hamstring-curl", name: "Flexora com TRX", muscles: ['hamstring'] },
  { id: "banded-standing-curl", name: "Flexora em Pé com Elástico", muscles: ['hamstring'] },
  { id: "front-lever", name: "Front Lever", muscles: ['upper-back', 'chest'] },
  { id: "cat-cow", name: "Gato-Vaca", muscles: ['lower-back', 'abs'] },
  { id: "plate-loaded-glute-drive", name: "Glute Drive com Anilha", muscles: ['gluteal'] },
  { id: "warrior-one", name: "Guerreiro I", muscles: ['gluteal', 'quadriceps'] },
  { id: "warrior-two", name: "Guerreiro II", muscles: ['gluteal', 'quadriceps'] },
  { id: "warrior-three", name: "Guerreiro III", muscles: ['gluteal', 'hamstring'] },
  { id: "kettlebell-halo", name: "Halo com Kettlebell", muscles: ['deltoids'] },
  { id: "hang-clean", name: "Hang Clean", muscles: ['gluteal', 'quadriceps', 'trapezius'] },
  { id: "hang-power-clean", name: "Hang Power Clean", muscles: ['gluteal', 'quadriceps', 'trapezius'] },
  { id: "hollow-body-hold", name: "Hollow Body Hold", muscles: ['abs'] },
  { id: "human-flag", name: "Human Flag (Bandeira Humana)", muscles: ['upper-back', 'obliques'] },
  { id: "jefferson-curl", name: "Jefferson Curl", muscles: ['lower-back', 'hamstring'] },
  { id: "double-kettlebell-jerk", name: "Jerk com 2 Kettlebells", muscles: ['deltoids', 'quadriceps'] },
  { id: "stability-ball-knee-tuck", name: "Joelho ao Peito com Bola Suíça", muscles: ['abs'] },
  { id: "tricep-kickback", name: "Kickback de Tríceps com Halteres", muscles: ['triceps'] },
  { id: "cable-tricep-kickback", name: "Kickback de Tríceps no Cabo", muscles: ['triceps'] },
  { id: "one-arm-kettlebell-tricep-kickback", name: "Kickback de Tríceps Unilateral com Kettlebell", muscles: ['triceps'] },
  { id: "l-sit", name: "L-Sit", muscles: ['quadriceps', 'abs'] },
  { id: "horizontal-leg-press", name: "Leg Press Horizontal", muscles: ['gluteal', 'quadriceps'] },
  { id: "wide-stance-leg-press", name: "Leg Press Pés Afastados", muscles: ['adductors'] },
  { id: "high-foot-leg-press", name: "Leg Press Pés Altos", muscles: ['gluteal'] },
  { id: "close-stance-leg-press", name: "Leg Press Pés Fechados", muscles: ['quadriceps'] },
  { id: "single-leg-press", name: "Leg Press Unilateral", muscles: ['gluteal', 'quadriceps'] },
  { id: "bench-leg-pull-in", name: "Leg Pull-In no Banco", muscles: ['abs'] },
  { id: "hex-bar-deadlift", name: "Levantamento Terra com Barra Hexagonal", muscles: ['lower-back', 'gluteal', 'quadriceps'] },
  { id: "dumbbell-deadlift", name: "Levantamento Terra com Halteres", muscles: ['lower-back', 'gluteal', 'hamstring'] },
  { id: "kettlebell-deadlift", name: "Levantamento Terra com Kettlebell", muscles: ['lower-back', 'gluteal', 'hamstring'] },
  { id: "deficit-deadlift", name: "Levantamento Terra em Déficit", muscles: ['lower-back', 'gluteal', 'hamstring'] },
  { id: "double-db-kickstand-deadlift", name: "Levantamento Terra Kickstand com 2 Halteres", muscles: ['gluteal', 'hamstring'] },
  { id: "db-kickstand-deadlift", name: "Levantamento Terra Kickstand com Halteres", muscles: ['gluteal', 'hamstring'] },
  { id: "kettlebell-kickstand-deadlift", name: "Levantamento Terra Kickstand com Kettlebell", muscles: ['gluteal', 'hamstring'] },
  { id: "pause-deadlift", name: "Levantamento Terra Pausado", muscles: ['lower-back', 'gluteal', 'hamstring'] },
  { id: "romanian-deadlift", name: "Levantamento Terra Romeno (RDL)", muscles: ['gluteal', 'hamstring'] },
  { id: "ez-bar-romanian-deadlift", name: "Levantamento Terra Romeno com Barra W", muscles: ['gluteal', 'hamstring'] },
  { id: "banded-romanian-deadlift", name: "Levantamento Terra Romeno com Elástico", muscles: ['gluteal', 'hamstring'] },
  { id: "dumbbell-romanian-deadlift", name: "Levantamento Terra Romeno com Halteres", muscles: ['gluteal', 'hamstring'] },
  { id: "smith-machine-rdl", name: "Levantamento Terra Romeno no Smith", muscles: ['hamstring'] },
  { id: "single-leg-romanian-deadlift", name: "Levantamento Terra Romeno Unilateral", muscles: ['gluteal', 'hamstring'] },
  { id: "one-arm-single-leg-dumbbell-romanian-deadlift", name: "Levantamento Terra Romeno Unilateral com 1 Halteres", muscles: ['gluteal', 'hamstring'] },
  { id: "one-arm-single-leg-kettlebell-romanian-deadlift", name: "Levantamento Terra Romeno Unilateral com 1 Kettlebell", muscles: ['gluteal', 'hamstring'] },
  { id: "sumo-deadlift", name: "Levantamento Terra Sumô", muscles: ['gluteal', 'quadriceps'] },
  { id: "kettlebell-sumo-deadlift", name: "Levantamento Terra Sumô com Kettlebell", muscles: ['gluteal', 'quadriceps'] },
  { id: "kettlebell-single-leg-deadlift", name: "Levantamento Terra Unilateral com Kettlebell", muscles: ['gluteal', 'hamstring'] },
  { id: "supine-windshield-wipers", name: "Limpador de Para-brisa Deitado", muscles: ['obliques', 'abs'] },
  { id: "assisted-dips", name: "Mergulho Assistido na Máquina", muscles: ['chest', 'triceps'] },
  { id: "crab-dips", name: "Mergulho Caranguejo (Crab Dips)", muscles: ['triceps'] },
  { id: "weighted-dips", name: "Mergulho com Peso", muscles: ['chest', 'triceps'] },
  { id: "straight-bar-dips", name: "Mergulho na Barra Reta", muscles: ['chest'] },
  { id: "reverse-plank-dips", name: "Mergulho na Prancha Reversa", muscles: ['triceps'] },
  { id: "ring-dips", name: "Mergulho nas Argolas", muscles: ['chest', 'triceps'] },
  { id: "bench-dips", name: "Mergulho no Banco", muscles: ['triceps'] },
  { id: "dips", name: "Mergulho para Peito (Dips)", muscles: ['chest', 'triceps'] },
  { id: "single-leg-lying-leg-curl", name: "Mesa Flexora Unilateral", muscles: ['hamstring'] },
  { id: "muscle-snatch", name: "Muscle Snatch", muscles: ['deltoids', 'trapezius'] },
  { id: "muscle-ups", name: "Muscle-Up", muscles: ['upper-back', 'triceps'] },
  { id: "ring-muscle-up", name: "Muscle-Up nas Argolas", muscles: ['upper-back', 'chest', 'triceps'] },
  { id: "cable-pallof-press", name: "Pallof Press no Cabo", muscles: ['obliques', 'abs'] },
  { id: "hanging-pike", name: "Pike na Barra", muscles: ['abs'] },
  { id: "ball-pike", name: "Pike na Bola Suíça", muscles: ['obliques', 'abs'] },
  { id: "pilates-spine-stretch-forward", name: "Pilates: Alongamento de Coluna para Frente", muscles: ['lower-back', 'abs'] },
  { id: "pilates-kneeling-side-kick", name: "Pilates: Chute Lateral Ajoelhado", muscles: ['gluteal', 'obliques'] },
  { id: "pilates-side-bend", name: "Pilates: Flexão Lateral", muscles: ['gluteal', 'obliques'] },
  { id: "pilates-leg-pull-back", name: "Pilates: Leg Pull Back", muscles: ['lower-back', 'gluteal'] },
  { id: "pilates-leg-pull-front", name: "Pilates: Leg Pull Front", muscles: ['gluteal', 'abs'] },
  { id: "pilates-roll-down", name: "Pilates: Roll Down", muscles: ['lower-back'] },
  { id: "pilates-roll-over", name: "Pilates: Roll Over", muscles: ['abs'] },
  { id: "pilates-saw", name: "Pilates: Serra", muscles: ['lower-back', 'obliques'] },
  { id: "pilates-spine-twist", name: "Pilates: Torção de Coluna", muscles: ['obliques'] },
  { id: "plate-pinch", name: "Pinça de Anilha (Plate Pinch)", muscles: ['forearm'] },
  { id: "planche", name: "Planche", muscles: ['deltoids', 'chest'] },
  { id: "jumping-jacks", name: "Polichinelo", muscles: ['calves', 'gluteal', 'deltoids'] },
  { id: "glute-bridge", name: "Ponte de Glúteo", muscles: ['gluteal'] },
  { id: "barbell-glute-bridge", name: "Ponte de Glúteo com Barra", muscles: ['gluteal'] },
  { id: "stability-ball-hip-bridge", name: "Ponte de Glúteo com Bola Suíça", muscles: ['gluteal'] },
  { id: "banded-glute-bridge", name: "Ponte de Glúteo com Elástico", muscles: ['gluteal'] },
  { id: "one-arm-kettlebell-floor-glute-bridge-press", name: "Ponte de Glúteo com Supino Unilateral no Kettlebell", muscles: ['gluteal', 'chest'] },
  { id: "glute-bridge-hold", name: "Ponte de Glúteo Isométrica", muscles: ['gluteal'] },
  { id: "single-leg-glute-bridge", name: "Ponte de Glúteo Unilateral", muscles: ['gluteal'] },
  { id: "single-leg-glute-bridge-hold", name: "Ponte de Glúteo Unilateral, Isométrico", muscles: ['gluteal'] },
  { id: "thoracic-bridge", name: "Ponte Torácica", muscles: ['lower-back', 'gluteal'] },
  { id: "head-to-knee-pose", name: "Postura Cabeça no Joelho", muscles: ['lower-back', 'hamstring'] },
  { id: "eagle-pose", name: "Postura da Águia", muscles: ['gluteal', 'quadriceps'] },
  { id: "tree-pose", name: "Postura da Árvore", muscles: ['gluteal', 'quadriceps'] },
  { id: "chair-pose", name: "Postura da Cadeira", muscles: ['gluteal', 'quadriceps'] },
  { id: "revolved-chair-pose", name: "Postura da Cadeira Revolvida", muscles: ['obliques', 'quadriceps'] },
  { id: "cobra-stretch", name: "Postura da Cobra", muscles: ['abs'] },
  { id: "childs-pose", name: "Postura da Criança", muscles: ['lower-back', 'upper-back'] },
  { id: "bench-childs-pose", name: "Postura da Criança no Banco", muscles: ['lower-back', 'upper-back'] },
  { id: "sphinx-pose", name: "Postura da Esfinge", muscles: ['lower-back'] },
  { id: "garland-pose", name: "Postura da Guirlanda", muscles: ['adductors', 'gluteal'] },
  { id: "half-moon-pose", name: "Postura da Meia-Lua", muscles: ['gluteal', 'obliques'] },
  { id: "mountain-pose", name: "Postura da Montanha", muscles: ['lower-back'] },
  { id: "pyramid-pose", name: "Postura da Pirâmide", muscles: ['hamstring'] },
  { id: "legs-up-the-wall", name: "Postura das Pernas na Parede", muscles: ['hamstring'] },
  { id: "extended-side-angle", name: "Postura do Ângulo Lateral Estendido", muscles: ['obliques', 'quadriceps'] },
  { id: "plow-pose", name: "Postura do Arado", muscles: ['lower-back', 'hamstring'] },
  { id: "bow-pose", name: "Postura do Arco", muscles: ['lower-back', 'gluteal'] },
  { id: "boat-pose", name: "Postura do Barco", muscles: ['quadriceps', 'abs'] },
  { id: "happy-baby", name: "Postura do Bebê Feliz", muscles: ['adductors', 'gluteal'] },
  { id: "savasana", name: "Postura do Cadáver (Savasana)", muscles: ['lower-back'] },
  { id: "camel-pose", name: "Postura do Camelo", muscles: ['lower-back', 'quadriceps'] },
  { id: "crow-pose", name: "Postura do Corvo", muscles: ['deltoids', 'triceps'] },
  { id: "dancer-pose", name: "Postura do Dançarino", muscles: ['gluteal', 'quadriceps'] },
  { id: "puppy-pose", name: "Postura do Filhote", muscles: ['upper-back', 'deltoids'] },
  { id: "locust-pose", name: "Postura do Gafanhoto", muscles: ['lower-back', 'gluteal'] },
  { id: "dolphin-pose", name: "Postura do Golfinho", muscles: ['deltoids', 'trapezius'] },
  { id: "hero-pose", name: "Postura do Herói", muscles: ['quadriceps'] },
  { id: "fish-pose", name: "Postura do Peixe", muscles: ['lower-back', 'chest'] },
  { id: "cow-face-pose", name: "Postura do Rosto de Vaca", muscles: ['gluteal'] },
  { id: "triangle-pose", name: "Postura do Triângulo", muscles: ['hamstring', 'obliques'] },
  { id: "easy-pose", name: "Postura Fácil", muscles: ['lower-back'] },
  { id: "plank", name: "Prancha", muscles: ['abs'] },
  { id: "high-plank", name: "Prancha Alta", muscles: ['abs'] },
  { id: "side-plank", name: "Prancha Lateral", muscles: ['obliques', 'abs'] },
  { id: "side-plank-leg-lift", name: "Prancha Lateral com Elevação de Perna", muscles: ['gluteal', 'obliques'] },
  { id: "side-plank-leg-lift-hold", name: "Prancha Lateral com Elevação de Perna, Isométrico", muscles: ['gluteal', 'obliques'] },
  { id: "trx-side-plank", name: "Prancha Lateral no TRX", muscles: ['obliques', 'abs'] },
  { id: "trx-plank", name: "Prancha no TRX", muscles: ['abs'] },
  { id: "reverse-plank", name: "Prancha Reversa", muscles: ['lower-back', 'gluteal'] },
  { id: "jump-rope", name: "Pular Corda", muscles: ['calves'] },
  { id: "band-pull-apart", name: "Pull-Apart com Elástico", muscles: ['deltoids'] },
  { id: "straight-arm-pulldown", name: "Pull-down com Braços Estendidos", muscles: ['upper-back'] },
  { id: "plate-pullover", name: "Pullover com Anilha", muscles: ['upper-back', 'chest'] },
  { id: "barbell-pullover", name: "Pullover com Barra", muscles: ['upper-back', 'chest'] },
  { id: "ez-bar-pullover", name: "Pullover com Barra W", muscles: ['upper-back', 'chest'] },
  { id: "bent-arm-ez-bar-pullover", name: "Pullover com Barra W, Braços Flexionados", muscles: ['upper-back', 'chest'] },
  { id: "bent-arm-barbell-pullover", name: "Pullover com Barra, Braços Flexionados", muscles: ['upper-back', 'chest'] },
  { id: "kettlebell-pullover", name: "Pullover com Kettlebell", muscles: ['upper-back', 'chest'] },
  { id: "floor-kettlebell-pullover", name: "Pullover no Chão com Kettlebell", muscles: ['upper-back', 'chest'] },
  { id: "push-jerk", name: "Push Jerk", muscles: ['deltoids', 'triceps'] },
  { id: "push-press", name: "Push Press", muscles: ['deltoids'] },
  { id: "double-kettlebell-push-press", name: "Push Press com 2 Kettlebells", muscles: ['deltoids'] },
  { id: "dumbbell-push-press", name: "Push Press com Halteres", muscles: ['deltoids', 'triceps'] },
  { id: "one-arm-dumbbell-push-press", name: "Push Press Unilateral com Halteres", muscles: ['deltoids'] },
  { id: "one-arm-kettlebell-push-press", name: "Push Press Unilateral com Kettlebell", muscles: ['deltoids'] },
  { id: "behind-the-neck-lat-pulldown", name: "Puxada Atrás da Nuca", muscles: ['upper-back'] },
  { id: "v-bar-lat-pulldown", name: "Puxada com Barra V", muscles: ['upper-back'] },
  { id: "close-grip-lat-pulldown", name: "Puxada Pegada Fechada", muscles: ['upper-back'] },
  { id: "reverse-grip-lat-pulldown", name: "Puxada Pegada Invertida", muscles: ['biceps', 'upper-back'] },
  { id: "one-arm-lat-pulldown", name: "Puxada Unilateral", muscles: ['upper-back'] },
  { id: "rack-pull", name: "Rack Pull", muscles: ['lower-back', 'gluteal', 'hamstring'] },
  { id: "upright-row", name: "Remada Alta com Barra", muscles: ['deltoids', 'trapezius'] },
  { id: "ez-bar-upright-row", name: "Remada Alta com Barra W", muscles: ['deltoids', 'trapezius'] },
  { id: "dumbbell-upright-row", name: "Remada Alta com Halteres", muscles: ['deltoids', 'trapezius'] },
  { id: "cable-upright-row", name: "Remada Alta no Cabo", muscles: ['deltoids', 'trapezius'] },
  { id: "smith-machine-upright-row", name: "Remada Alta no Smith", muscles: ['deltoids', 'trapezius'] },
  { id: "t-bar-row", name: "Remada Cavalinho (T-Bar)", muscles: ['upper-back'] },
  { id: "double-kettlebell-row", name: "Remada com 2 Kettlebells", muscles: ['upper-back'] },
  { id: "chest-supported-db-row", name: "Remada com Halteres Apoiado no Banco", muscles: ['upper-back'] },
  { id: "chest-supported-kettlebell-row", name: "Remada com Kettlebell Apoiado no Banco", muscles: ['upper-back'] },
  { id: "bent-over-ez-bar-row", name: "Remada Curvada com Barra W", muscles: ['upper-back'] },
  { id: "bent-over-db-row", name: "Remada Curvada com Halteres", muscles: ['upper-back'] },
  { id: "cable-bent-over-row", name: "Remada Curvada no Cabo", muscles: ['upper-back'] },
  { id: "smith-machine-bent-over-row", name: "Remada Curvada no Smith", muscles: ['upper-back'] },
  { id: "reverse-grip-bent-over-row", name: "Remada Curvada Pegada Invertida", muscles: ['upper-back'] },
  { id: "smith-machine-reverse-grip-bent-over-row", name: "Remada Curvada Pegada Invertida no Smith", muscles: ['biceps', 'upper-back'] },
  { id: "inverted-row", name: "Remada Invertida", muscles: ['upper-back', 'trapezius'] },
  { id: "rings-inverted-row", name: "Remada Invertida nas Argolas", muscles: ['upper-back', 'trapezius'] },
  { id: "ring-row", name: "Remada nas Argolas", muscles: ['upper-back'] },
  { id: "bench-pull", name: "Remada no Banco", muscles: ['upper-back'] },
  { id: "dumbbell-bench-pull", name: "Remada no Banco com Halteres", muscles: ['upper-back'] },
  { id: "kneeling-cable-row", name: "Remada no Cabo Ajoelhado", muscles: ['upper-back'] },
  { id: "chest-supported-smith-machine-row", name: "Remada no Smith Apoiado no Banco", muscles: ['upper-back'] },
  { id: "sled-row", name: "Remada no Trenó", muscles: ['upper-back'] },
  { id: "trx-row", name: "Remada no TRX", muscles: ['upper-back'] },
  { id: "double-kettlebell-rear-delt-row", name: "Remada para Deltoide Posterior com 2 Kettlebells", muscles: ['deltoids', 'upper-back'] },
  { id: "barbell-rear-delt-row", name: "Remada para Deltoide Posterior com Barra", muscles: ['deltoids'] },
  { id: "ez-bar-reverse-grip-row", name: "Remada Pegada Invertida com Barra W", muscles: ['biceps', 'upper-back'] },
  { id: "pendlay-row", name: "Remada Pendlay", muscles: ['upper-back', 'trapezius'] },
  { id: "seated-cable-row", name: "Remada Sentada no Cabo", muscles: ['upper-back'] },
  { id: "wide-grip-seated-cable-row", name: "Remada Sentada Pegada Aberta", muscles: ['upper-back'] },
  { id: "single-arm-db-row", name: "Remada Unilateral com Halteres", muscles: ['upper-back'] },
  { id: "single-arm-chest-supported-dumbbell-row", name: "Remada Unilateral com Halteres Apoiado no Banco", muscles: ['upper-back'] },
  { id: "one-arm-kettlebell-row", name: "Remada Unilateral com Kettlebell", muscles: ['upper-back'] },
  { id: "rowing-machine", name: "Remo Ergométrico", muscles: ['upper-back', 'quadriceps'] },
  { id: "chin-tuck-hold", name: "Retração de Queixo (Chin Tuck)", muscles: ['trapezius'] },
  { id: "reverse-tabletop-hip-pulses", name: "Reverse Tabletop com Pulsos de Quadril", muscles: ['gluteal'] },
  { id: "reverse-tabletop-hold", name: "Reverse Tabletop Isométrico", muscles: ['lower-back', 'gluteal'] },
  { id: "ab-wheel-rollout", name: "Rolamento com Roda Abdominal", muscles: ['abs'] },
  { id: "barbell-ab-rollout", name: "Rolamento com Roda Abdominal (Barra)", muscles: ['abs'] },
  { id: "double-kettlebell-bicep-curl", name: "Rosca Bíceps com 2 Kettlebells", muscles: ['biceps'] },
  { id: "trx-bicep-curl", name: "Rosca Bíceps no TRX", muscles: ['biceps'] },
  { id: "one-arm-kettlebell-bicep-curl", name: "Rosca Bíceps Unilateral com Kettlebell", muscles: ['biceps'] },
  { id: "cheat-curl", name: "Rosca Cheat (Rosca Trapaça)", muscles: ['biceps'] },
  { id: "close-grip-ez-bar-curl", name: "Rosca com Barra W Pegada Fechada", muscles: ['biceps'] },
  { id: "concentration-curl", name: "Rosca Concentrada", muscles: ['biceps'] },
  { id: "kettlebell-concentration-curl", name: "Rosca Concentrada com Kettlebell", muscles: ['biceps'] },
  { id: "wrist-curl", name: "Rosca de Punho Bilateral com Halteres", muscles: ['forearm'] },
  { id: "barbell-wrist-curl", name: "Rosca de Punho com Barra", muscles: ['forearm'] },
  { id: "ez-bar-wrist-curl", name: "Rosca de Punho com Barra W", muscles: ['forearm'] },
  { id: "dumbbell-wrist-curl", name: "Rosca de Punho com Halteres", muscles: ['forearm'] },
  { id: "kettlebell-wrist-curl", name: "Rosca de Punho com Kettlebell", muscles: ['forearm'] },
  { id: "db-reverse-wrist-curl", name: "Rosca de Punho Invertida com Halteres", muscles: ['forearm'] },
  { id: "kettlebell-reverse-wrist-curl", name: "Rosca de Punho Invertida com Kettlebell", muscles: ['forearm'] },
  { id: "cable-wrist-curl", name: "Rosca de Punho no Cabo", muscles: ['forearm'] },
  { id: "ez-bar-curl", name: "Rosca Direta com Barra W", muscles: ['biceps'] },
  { id: "bicep-curl", name: "Rosca Direta com Halteres", muscles: ['biceps'] },
  { id: "machine-bicep-curl", name: "Rosca Direta na Máquina", muscles: ['biceps'] },
  { id: "cable-curl", name: "Rosca Direta no Cabo", muscles: ['biceps'] },
  { id: "close-grip-barbell-curl", name: "Rosca Direta Pegada Fechada", muscles: ['biceps'] },
  { id: "drag-curl", name: "Rosca Drag", muscles: ['biceps'] },
  { id: "strict-curl", name: "Rosca Estrita", muscles: ['biceps'] },
  { id: "incline-db-curl", name: "Rosca Inclinada com Halteres", muscles: ['biceps'] },
  { id: "reverse-curl", name: "Rosca Invertida", muscles: ['biceps', 'forearm'] },
  { id: "ez-bar-reverse-curl", name: "Rosca Invertida com Barra W", muscles: ['biceps', 'forearm'] },
  { id: "db-reverse-curl", name: "Rosca Invertida com Halteres", muscles: ['biceps', 'forearm'] },
  { id: "hammer-curl", name: "Rosca Martelo com Halteres", muscles: ['biceps'] },
  { id: "kettlebell-hammer-curl", name: "Rosca Martelo com Kettlebell", muscles: ['biceps'] },
  { id: "cross-body-hammer-curl", name: "Rosca Martelo Cruzada", muscles: ['biceps'] },
  { id: "incline-hammer-curl", name: "Rosca Martelo Inclinada", muscles: ['biceps'] },
  { id: "preacher-hammer-curl", name: "Rosca Martelo no Banco Scott", muscles: ['biceps'] },
  { id: "cable-hammer-curl", name: "Rosca Martelo no Cabo", muscles: ['biceps'] },
  { id: "single-arm-hammer-curl", name: "Rosca Martelo Unilateral", muscles: ['biceps'] },
  { id: "nordic-hamstring-curl", name: "Rosca Nórdica (Nordic Curl)", muscles: ['hamstring'] },
  { id: "reverse-nordic-curl", name: "Rosca Nórdica Invertida", muscles: ['quadriceps'] },
  { id: "preacher-curl", name: "Rosca Scott", muscles: ['biceps'] },
  { id: "barbell-preacher-curl", name: "Rosca Scott com Barra", muscles: ['biceps'] },
  { id: "machine-preacher-curl", name: "Rosca Scott na Máquina", muscles: ['biceps'] },
  { id: "seated-dumbbell-curl", name: "Rosca Sentado com Halteres", muscles: ['biceps'] },
  { id: "spider-curl", name: "Rosca Spider (Rosca Aranha)", muscles: ['biceps'] },
  { id: "ez-bar-spider-curl", name: "Rosca Spider com Barra W", muscles: ['biceps'] },
  { id: "zottman-curl", name: "Rosca Zottman", muscles: ['biceps'] },
  { id: "cable-external-rotation", name: "Rotação Externa no Cabo", muscles: ['deltoids'] },
  { id: "russian-twist", name: "Russian Twist (Torção Russa)", muscles: ['obliques', 'abs'] },
  { id: "kettlebell-russian-twist", name: "Russian Twist com Kettlebell", muscles: ['obliques'] },
  { id: "box-jump", name: "Salto na Caixa (Box Jump)", muscles: ['gluteal', 'quadriceps'] },
  { id: "snatch", name: "Snatch (Arranco)", muscles: ['gluteal', 'quadriceps', 'trapezius'] },
  { id: "split-jerk", name: "Split Jerk", muscles: ['deltoids', 'quadriceps'] },
  { id: "double-kettlebell-split-jerk", name: "Split Jerk com 2 Kettlebells", muscles: ['deltoids', 'quadriceps'] },
  { id: "double-kettlebell-dead-split-snatch", name: "Split Snatch Parado com 2 Kettlebells", muscles: ['deltoids', 'gluteal'] },
  { id: "standing-split", name: "Splits em Pé", muscles: ['gluteal', 'hamstring'] },
  { id: "spoto-press", name: "Spoto Press", muscles: ['chest'] },
  { id: "step-ups", name: "Subida no Step (Step-Up)", muscles: ['gluteal', 'quadriceps'] },
  { id: "kettlebell-sumo-high-pull", name: "Sumo High Pull com Kettlebell", muscles: ['adductors', 'deltoids', 'trapezius'] },
  { id: "superman", name: "Superman", muscles: ['lower-back', 'gluteal'] },
  { id: "ez-bar-bench-press", name: "Supino com Barra W", muscles: ['chest'] },
  { id: "decline-bench-press", name: "Supino Declinado", muscles: ['chest'] },
  { id: "decline-bench-press-barbell", name: "Supino Declinado com Barra", muscles: ['chest'] },
  { id: "decline-bench-press-ez-bar", name: "Supino Declinado com Barra W", muscles: ['chest'] },
  { id: "smith-machine-decline-bench-press", name: "Supino Declinado no Smith", muscles: ['chest'] },
  { id: "close-grip-bench-press", name: "Supino Fechado", muscles: ['triceps'] },
  { id: "close-grip-ez-bar-bench-press", name: "Supino Fechado com Barra W", muscles: ['triceps'] },
  { id: "close-grip-db-bench-press", name: "Supino Fechado com Halteres", muscles: ['triceps'] },
  { id: "incline-bench-press", name: "Supino Inclinado com Barra", muscles: ['chest'] },
  { id: "incline-bench-ez-bar-press", name: "Supino Inclinado com Barra W", muscles: ['chest'] },
  { id: "incline-db-press", name: "Supino Inclinado com Halteres", muscles: ['chest'] },
  { id: "close-grip-incline-bench", name: "Supino Inclinado Fechado", muscles: ['triceps'] },
  { id: "smith-machine-incline-bench-press", name: "Supino Inclinado no Smith", muscles: ['deltoids', 'chest'] },
  { id: "paused-incline-bench-press", name: "Supino Inclinado Pausado", muscles: ['deltoids', 'chest'] },
  { id: "chest-press-machine", name: "Supino na Máquina", muscles: ['chest'] },
  { id: "cable-chest-press", name: "Supino no Cabo", muscles: ['chest'] },
  { id: "floor-press", name: "Supino no Chão", muscles: ['chest'] },
  { id: "floor-ez-bar-press", name: "Supino no Chão com Barra W", muscles: ['chest'] },
  { id: "dumbbell-floor-press", name: "Supino no Chão com Halteres", muscles: ['chest'] },
  { id: "kettlebell-floor-press", name: "Supino no Chão com Kettlebell", muscles: ['chest'] },
  { id: "kettlebell-close-grip-floor-press", name: "Supino no Chão Pegada Fechada com Kettlebell", muscles: ['triceps'] },
  { id: "one-arm-kettlebell-floor-press", name: "Supino no Chão Unilateral com Kettlebell", muscles: ['chest'] },
  { id: "smith-machine-bench-press", name: "Supino no Smith", muscles: ['chest'] },
  { id: "trx-chest-press", name: "Supino no TRX", muscles: ['chest'] },
  { id: "db-bench-press", name: "Supino Reto com Halteres", muscles: ['chest'] },
  { id: "paused-bench-press", name: "Supino Reto Pausado", muscles: ['chest'] },
  { id: "wide-grip-bench-press", name: "Supino Reto Pegada Aberta", muscles: ['chest'] },
  { id: "svend-press", name: "Svend Press", muscles: ['chest'] },
  { id: "single-db-svend-press", name: "Svend Press com 1 Halteres", muscles: ['chest'] },
  { id: "db-svend-press", name: "Svend Press com Halteres", muscles: ['chest'] },
  { id: "kettlebell-svend-press", name: "Svend Press com Kettlebell", muscles: ['chest'] },
  { id: "kettlebell-swing-clean", name: "Swing Clean com Kettlebell", muscles: ['gluteal', 'hamstring'] },
  { id: "kettlebell-swing", name: "Swing com Kettlebell", muscles: ['gluteal', 'hamstring'] },
  { id: "double-kettlebell-swing-snatch", name: "Swing Snatch com 2 Kettlebells", muscles: ['gluteal', 'hamstring'] },
  { id: "one-arm-dumbbell-swing", name: "Swing Unilateral com Halteres", muscles: ['gluteal', 'hamstring'] },
  { id: "one-arm-kettlebell-swing", name: "Swing Unilateral com Kettlebell", muscles: ['gluteal', 'hamstring'] },
  { id: "scissor-kicks", name: "Tesoura (Scissor Kicks)", muscles: ['quadriceps', 'abs'] },
  { id: "flutter-kicks", name: "Tesourinha (Flutter Kicks)", muscles: ['quadriceps', 'abs'] },
  { id: "thruster", name: "Thruster", muscles: ['deltoids', 'quadriceps'] },
  { id: "toes-to-bar", name: "Toes to Bar", muscles: ['quadriceps', 'abs'] },
  { id: "supine-spinal-twist", name: "Torção Espinhal Deitado", muscles: ['lower-back', 'obliques'] },
  { id: "seated-spinal-twist", name: "Torção Espinhal Sentado", muscles: ['lower-back', 'obliques'] },
  { id: "single-arm-tricep-pushdown", name: "Tríceps Corda Unilateral (Cabo)", muscles: ['triceps'] },
  { id: "overhead-tricep-extension", name: "Tríceps Francês (Acima da Cabeça)", muscles: ['triceps'] },
  { id: "barbell-overhead-extension", name: "Tríceps Francês com Barra", muscles: ['triceps'] },
  { id: "ez-bar-overhead-extension", name: "Tríceps Francês com Barra W", muscles: ['triceps'] },
  { id: "single-arm-dumbbell-overhead-tricep-extension", name: "Tríceps Francês Unilateral com Halteres", muscles: ['triceps'] },
  { id: "v-bar-tricep-pushdown", name: "Tríceps Pulley com Barra V", muscles: ['triceps'] },
  { id: "skull-crusher", name: "Tríceps Testa", muscles: ['triceps'] },
  { id: "lying-tricep-extension", name: "Tríceps Testa (Deitado)", muscles: ['triceps'] },
  { id: "ez-bar-lying-tricep-extension", name: "Tríceps Testa com Barra W", muscles: ['triceps'] },
  { id: "db-skull-crusher", name: "Tríceps Testa com Halteres", muscles: ['triceps'] },
  { id: "kettlebell-skull-crusher", name: "Tríceps Testa com Kettlebell", muscles: ['triceps'] },
  { id: "kettlebell-turkish-get-ups", name: "Turkish Get-Up com Kettlebell", muscles: ['deltoids', 'gluteal', 'abs'] },
  { id: "bear-crawl", name: "Urso (Bear Crawl)", muscles: ['deltoids', 'abs'] },
  { id: "v-sit", name: "V-Sit", muscles: ['quadriceps', 'abs'] },
  { id: "supported-shoulderstand", name: "Vela com Apoio", muscles: ['lower-back', 'abs'] },
  { id: "dumbbell-windmill", name: "Windmill com Halteres", muscles: ['deltoids', 'obliques'] },
  { id: "kettlebell-windmills", name: "Windmill com Kettlebell", muscles: ['adductors', 'deltoids', 'obliques'] },
  { id: "wrist-roller", name: "Wrist Roller (Rolo de Punho)", muscles: ['forearm'] },
];
