"""add goal type fields to challenges

Revision ID: 1d5cd7d51470
Revises: 91020df27fb9
Create Date: 2026-08-19 23:11:08.496070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5cd7d51470'
down_revision: Union[str, Sequence[str], None] = '91020df27fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # goal_type e NOT NULL — precisa de server_default pra nao quebrar as
    # linhas ja existentes (os 2 desafios oficiais ja em producao, e
    # qualquer desafio de profissional). 'manual' preserva exatamente o
    # comportamento atual (check-in binario via ChallengeCheckin) pra
    # TODOS os desafios existentes, sem exigir nenhuma reclassificacao —
    # decisao explicita, nao um efeito colateral do backfill.
    op.add_column('challenges', sa.Column('goal_type', sa.String(), nullable=False, server_default='manual'))
    op.add_column('challenges', sa.Column('target_value', sa.Float(), nullable=True))
    op.add_column('challenges', sa.Column('target_unit', sa.String(), nullable=True))
    op.add_column('challenges', sa.Column('target_frequency_per_week', sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'target_frequency_per_week')
    op.drop_column('challenges', 'target_unit')
    op.drop_column('challenges', 'target_value')
    op.drop_column('challenges', 'goal_type')
    # ### end Alembic commands ###
