"""add diet_plans table

Revision ID: 230a37099781
Revises: a1f3c9b7d2e4
Create Date: 2026-08-11 10:15:41.078045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230a37099781'
down_revision: Union[str, Sequence[str], None] = 'a1f3c9b7d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('daily_calorie_target', sa.Float(), nullable=True),
    sa.Column('daily_protein_target', sa.Float(), nullable=True),
    sa.Column('daily_carbs_target', sa.Float(), nullable=True),
    sa.Column('daily_fat_target', sa.Float(), nullable=True),
    sa.Column('plan_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diet_plans')
    # ### end Alembic commands ###
