"""add waitlist_emails table

Revision ID: 7e363954b50f
Revises: 826ea09fd191
Create Date: 2026-09-14 22:56:19.499712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e363954b50f'
down_revision: Union[str, Sequence[str], None] = '826ea09fd191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_emails_email'), 'waitlist_emails', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_emails_email'), table_name='waitlist_emails')
    op.drop_table('waitlist_emails')
    # ### end Alembic commands ###
