"""add professional_type to trainers

Revision ID: cb4f24d7119d
Revises: f0ae54618547
Create Date: 2026-08-03 13:22:33.818834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4f24d7119d'
down_revision: Union[str, Sequence[str], None] = 'f0ae54618547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default preenche as linhas existentes (todo professor cadastrado
    # ate hoje e educador fisico, ja que o cadastro de nutricionista ainda
    # nao existe) — sem isso, adicionar uma coluna NOT NULL falharia numa
    # tabela que ja tem linhas.
    op.add_column(
        'trainers',
        sa.Column('professional_type', sa.String(), nullable=False, server_default='personal_trainer'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'professional_type')
    # ### end Alembic commands ###
